name: 'Generate PHP docs with evert/phpdoc-md'
description: 'GitHub action to generate PHP project documentation in MarkDown format. Based on evert/phpdoc-md library.'

branding:
  icon: book
  color: red

inputs:
  ignored_files:
    description: "Defines files that can be ignored (supports glob rules; each line means one rule)"
    required: false
    default: ''
  phpdocumentor_version:
    description: "What phpDocumentor version to use? (latest or release tag like v2.8.5)"
    default: v2.8.5
    required: false
  output_path:
    description: "Path where to write generated documentation"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output_path }}
    - ${{ inputs.ignored_files }}
    - ${{ inputs.phpdocumentor_version }}
